//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpDeptMVVM.Models
{
    using System;
    using System.Collections.Generic;
    /// <summary>
    /// Model
    /// </summary>
    public partial class EMPLOYEE
    {
        public decimal EMPNO { get; set; }
        public string ENAME { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public string ROLE { get; set; }
        public Nullable<decimal> DEPTID { get; set; }
    }
}
